In [1]:
import pandas as pd
import plotly.graph_objects as go

In [2]:
df = pd.read_csv("cluster_attribute.csv")

In [3]:
# cloud_types = ['Cirrus', 'Cirrostratus', 'Stratus', 'Stratocumulus',
#                'Cumulus', 'Cirrocumulus', 'Nimbus', 'Clear']
cloud_types = [
    'Cirrus_weighted', 'Cirrostratus_weighted', 'Stratus_weighted', 'Stratocumulus_weighted',
    'Cumulus_weighted', 'Cirrocumulus_weighted', 'Nimbus_weighted', 'Clear_weighted'
]

colors = [
    '#FF4B4B','#FF9600','#FFD24B','#AFE182',
    '#82AFE1','#AF96FF','#969696','#000000'
]

monthly_sum = df.groupby('Month')[cloud_types].sum()
month_order = [3, 2, 1, 12, 11, 10]

existing_months_in_order = [m for m in month_order if m in monthly_sum.index]
monthly_sum = monthly_sum.reindex(existing_months_in_order)

fig = go.Figure()

# add a bar for each cloud type
for i, cloud_type in enumerate(cloud_types):
    fig.add_trace(go.Bar(
        y=monthly_sum.index, x=monthly_sum[cloud_type],
        name=cloud_type, marker_color=colors[i],
        orientation='h', showlegend=False
    ))

for cloud_type, color in zip(reversed(cloud_types), reversed(colors)):
    fig.add_trace(go.Scatter(
        x=[None], y=[None], mode='markers',
        marker=dict(size=12, color=color, symbol="square"),
        name=cloud_type.replace('_weighted', ''), showlegend=True, hoverinfo='skip'
    ))

fig.update_layout(
    barmode='stack',
    barnorm='percent',
    title_text='Monthly (Weighted) Cloud Type Distribution',
    title_x=0.5, title_y=0.95,
    yaxis_title='Month',
    xaxis_title='Percentage',
    legend_title='Type',
    font=dict(
        size=16
    ),
    yaxis=dict(
        type='category',
        categoryorder='array',
        categoryarray=monthly_sum.index
    ),
    width=1200, height=400,
    margin=dict(l=50, r=30, t=80, b=50),
    legend=dict(
        orientation="h",
        yanchor="bottom",
        x=1, y=1.02,
        xanchor="right"
    )
)

fig.show()

In [4]:
monthly_sum = df.groupby('Month')[cloud_types].sum()
month_order = [10, 11, 12, 1, 2, 3, 4]
existing_months_in_order = [m for m in month_order if m in monthly_sum.index]
monthly_sum = monthly_sum.reindex(existing_months_in_order)

monthly_percent = monthly_sum.div(monthly_sum.sum(axis=1), axis=0) * 100
monthly_percent = monthly_percent.round(1)
monthly_percent.columns = [ct.replace('_weighted','') for ct in monthly_percent.columns]
monthly_percent = monthly_percent.astype(str) + '%'
monthly_percent

,Cirrus,Cirrostratus,Stratus,Stratocumulus,Cumulus,Cirrocumulus,Nimbus,Clear
Month,,,,,,,,
10,0.1%,0.6%,15.7%,23.2%,1.0%,1.6%,50.0%,7.7%
11,0.1%,0.5%,27.9%,23.7%,1.3%,2.2%,31.1%,13.3%
12,0.2%,1.0%,18.3%,15.5%,1.1%,1.3%,44.8%,17.9%
1,0.0%,0.1%,19.9%,21.2%,1.5%,1.0%,52.8%,3.5%
2,0.0%,0.3%,15.8%,8.8%,0.5%,1.9%,70.5%,2.3%
3,0.4%,2.1%,28.9%,15.7%,0.6%,0.6%,43.5%,8.2%

In [5]:
# Define label order
labels = [1, 2, 3]

# Calculate the count of each label for each month
monthly_label_counts = df.groupby(['Month', 'label']).size().unstack(fill_value=0)

# Define month order
month_order = [10, 11, 12, 1, 2, 3]

# Reindex to sort months and ensure all months are present
existing_months_in_order = [m for m in month_order if m in monthly_label_counts.index]
monthly_label_counts = monthly_label_counts.reindex(existing_months_in_order)

fig = go.Figure()

# Add a bar for each label
for label in labels:
    if label in monthly_label_counts.columns:
        fig.add_trace(go.Bar(
            x=monthly_label_counts.index,
            y=monthly_label_counts[label],
            name=str(label)
        ))

fig.update_layout(
    barmode='stack',
    barnorm='percent',
    title_text='Monthly Cluster Distribution',
    title_x=0.5, title_y=0.95,
    xaxis_title='Month',
    yaxis_title='Percentage',
    legend_title='Cluster',
    font=dict(
        size=16
    ),
    xaxis=dict(
        type='category',
        categoryorder='array',
        categoryarray=monthly_label_counts.index
    ),
    width=500, height=400,
    margin=dict(l=50, r=20, t=80, b=50),
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=0.83
    )
)

fig.show()

In [6]:
labels = [1, 2, 3]
monthly_label_counts = df.groupby(['Month', 'label']).size().unstack(fill_value=0)
month_order = [10, 11, 12, 1, 2, 3]
existing_months_in_order = [m for m in month_order if m in monthly_label_counts.index]
monthly_label_counts = monthly_label_counts.reindex(existing_months_in_order)

monthly_label_percent = monthly_label_counts[labels].div(monthly_label_counts[labels].sum(axis=1), axis=0) * 100
monthly_label_percent = monthly_label_percent.round(1)
monthly_label_percent.columns = [f'Cluster {l}' for l in labels]
monthly_label_percent = monthly_label_percent.astype(str) + '%'
monthly_label_percent

      Cluster 1 Cluster 2 Cluster 3
Month
10         8.2%     29.9%     62.0%
11        19.3%     24.0%     56.7%
12        32.3%     12.8%     55.0%
1          8.5%     11.1%     80.4%
2          9.0%      9.9%     81.1%
3         11.1%     29.8%     59.2%

### For case study

In [7]:
df = pd.read_csv("cluster_attribute_case.csv")

In [8]:
# cloud_types = ['Cirrus', 'Cirrostratus', 'Stratus', 'Stratocumulus',
#                'Cumulus', 'Cirrocumulus', 'Nimbus', 'Clear']
cloud_types = [
    'Cirrus_weighted', 'Cirrostratus_weighted', 'Stratus_weighted', 'Stratocumulus_weighted',
    'Cumulus_weighted', 'Cirrocumulus_weighted', 'Nimbus_weighted', 'Clear_weighted'
]

colors = [
    '#FF4B4B','#FF9600','#FFD24B','#AFE182',
    '#82AFE1','#AF96FF','#969696','#000000'
]

df['Date'] = pd.to_datetime(df[['Year', 'Month', 'Day']])
daily_sum = df.groupby('Date')[cloud_types].sum()
daily_sum.index = pd.to_datetime(daily_sum.index)
daily_sum = daily_sum.sort_index()

fig = go.Figure()

# add a bar for each cloud type
for i, cloud_type in enumerate(cloud_types):
    fig.add_trace(go.Bar(
        y=daily_sum.index.strftime('%Y-%m-%d'), x=daily_sum[cloud_type],
        name=cloud_type, marker_color=colors[i],
        orientation='h', showlegend=False
    ))

for cloud_type, color in zip(reversed(cloud_types), reversed(colors)):
    fig.add_trace(go.Scatter(
        x=[None], y=[None], mode='markers',
        marker=dict(size=24, color=color, symbol="square"),
        name=cloud_type.replace('_weighted', ''), showlegend=True, hoverinfo='skip'
    ))

fig.update_layout(
    barmode='stack',
    barnorm='percent',
    yaxis_title='Date',
    xaxis_title='Percentage',
    legend_title='Type',
    font=dict(size=24, family='Arial', weight='bold'),
    yaxis=dict(
        type='category',
        categoryorder='array',
        categoryarray=daily_sum.index.strftime('%Y-%m-%d')
    ),
    width=1500, height=1000,
    margin=dict(l=100, r=30, t=10, b=50),
    legend=dict(
        orientation="h",
        yanchor="bottom",
        x=1, y=1.02,
        xanchor="right"
    )
)

fig.show()